package:                                                                        
  name: plurmy                                                       
  version: 0.1.0                                                                
                                                                                
source:                                                                         
   git_url: https://github.com/USGS-Astrogeology/plurmy.git            
                                                                                
requirements:                                                                   
  build:                                                                        
    - python                                                                    

  run:                                                                          
    - python                                                                    
